apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels: 
    app: my-app
    component: reactjs-app
spec:
  containers:
  - name: authentication-container
    image: authentication:v1
    imagePullPolicy: Never
    # ports:
    # - containerPort: 5000
    envFrom:
    - configMapRef:
        name: agile-env
  - name: reactjs-container
    image: reactjs:v1
    imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: NodePort
  selector:
    app: my-app
    component: reactjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: my-app
    component: reactjs-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


