---
apiVersion: v1
kind: Service
metadata:
  name: reactjs-service
spec:
  type: NodePort
  selector:
    app: my-app
    component: reactjs-container
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: my-app
    component: authentication-container
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


# apiVersion: v1
# kind: Service
# metadata:
#   name: reactjs-service
# spec:
#   selector:
#     app: react-app
#   ports:
#     - protocol: TCP
#       port: 3000  
#       targetPort: 3000
#   type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: authentication-service
# spec:
#   selector:
#     app: react-app
#   ports:
#     - protocol: TCP
#       port: 3000  
#       targetPort: 3000
#   type: LoadBalancer
